# Generated by Django 4.2.7 on 2023-11-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='colour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
